FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

RUN apt-get update && apt-get install -y \
    tzdata \
    git \
    wget \
    curl \
    nano \
    unzip \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install \
    torch torchvision torchaudio \
    transformers==4.36.2 accelerate==0.27.2 \
    pandas openpyxl datasets scikit-learn \
    sentencepiece protobuf matplotlib
