FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime

RUN apt-get update && apt-get install -y \
    tzdata \
    git \
    wget \
    curl \
    nano \
    unzip \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    util-linux \
    tree \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install \
    torch torchvision torchaudio \
    transformers==4.45.2 \
    pandas openpyxl datasets scikit-learn \
    sentencepiece>=0.2.0 \
    protobuf matplotlib \
    peft==0.15.2 \
    accelerate>=0.33.0 \
    bitsandbytes==0.45.2 \
    deepspeed \
    trl
